server:
  port: 8081
node:
  id: 1
  port: 8081
  nodes:
    - id: 0
      host: localhost
      port: 8080
    - id: 1
      host: localhost
      port: 8081
    - id: 2
      host: localhost
      port: 8082