version: '3.8'

services:
  redis:
    image: arm64v8/redis:7.4-bookworm  # ARM64-compatible Redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  java-app:
    build:
      context: ..
      dockerfile: Dockerfile  # Your Java app's Dockerfile
    container_name: java-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

volumes:
  redis_data:  # Persist Redis data